### ISSUE TITLE
Enum inside other Enum

### ISSUE THREAD

**Issue by jairocgr** [beerlington/classy_enum#56] opened 2016-03-12 10:13 UTC
Currently, can one classy_enum type hold another classy_enum value?

:smiley:

**Comment by beerlington** [comment] 2016-03-12 13:05
I'm not sure I follow. Can you give an example of what you're trying to do?

**Comment by jairocgr** [comment] 2016-03-12 16:28
I'm wrinting the user system for a webapp. 

In this app, every user has a level:

```ruby
class User < ActiveRecord::Base
  include ClassyEnum::ActiveRecord

end
```

```ruby
class UserLevel < ClassyEnum::Base
  include ActiveModel::Model
  include ClassyEnum::ActiveRecord

  attr_accessor :weight, :color, :category

  classy_enum_attr :climate
end
```

```ruby
class UserCategory < ClassyEnum::Base
  include ActiveModel::Model

  attr_accessor :weight, :color
end
```

**Comment by jairocgr** [comment] 2016-03-12 16:58
I'm wrinting the user system for a webapp based on user levels and weights.

In this app, each user has a level.

```ruby
class User < ActiveRecord::Base
  include ClassyEnum::ActiveRecord

  classy_enum_attr :level, class_name: 'UserLevel'

  # ...
end
```

The user level is a enumerated type. Each level has its own attributes.

```ruby
class UserLevel < ClassyEnum::Base
  include ActiveModel::Model
  include ClassyEnum::ActiveRecord

  attr_accessor :weight, :color, :category

  classy_enum_attr :category, class_name: 'UserCategory'
end

class UserLevel::Root < UserLevel
  def initialize
    super(weight: 10000, color: 'red')
  end
end

class UserLevel::System < UserLevel
  def initialize
    super(weight: 9000, color: 'orange')
  end
end

class UserLevel::Developer < UserLevel  # 8 other user levels...
```

Each level has his own category.

```ruby
class UserCategory < ClassyEnum::Base
  include ActiveModel::Model

  attr_accessor :weight, :color
end

class UserCategory::Root < UserCategory
  def initialize
    super(weight: 10000, color: 'red')
  end
end

class UserCategory::DevelopmentTeam < UserCategory
  def initialize
    super(weight: 900, color: '#d7c200')
  end
end

class UserCategory::MaintenanceCrew < UserCategory
  def initialize
    super(weight: 900, color: 'orange')
  end
end

class UserCategory::Tenanted < UserCategory
  def initialize
    super(weight: 800, color: 'blue') # 3 other categories...
```

I tried this, but i've got and exception raised inside `classy_enum_attr`.

I read the `ClassyEnum::ActiveRecord` code and seems that `classy_enum_attr` method assume that it is aways called insid a `ActiveRecord` class.

The `classy_enum_attr` attribute seems to use `ActiveRecord's` `read_attribute` method for create its own accessors.

**Comment by beerlington** [comment] 2016-03-15 16:10
@jairocgr thanks for the example. The piece I'm confused on is how you would store this data structure. If an enum value like "level" maps to a string field in the database, you wouldn't be able to keep track of the category within that. It seems like your data structure might be more complex than what Classy Enum was designed for. 

Would it be possible to have two different database fields? one for level and another for category?

**Comment by jairocgr** [comment] 2016-03-15 17:01
> Would it be possible to have two different database fields? one for level and another for category?

Yes, it would. But i don't want to do that.

Maybe you're right. Maybe classy_enum isn't fit for this job in particulary.

But classy_enum it's a very fine gem! I'll continue to use it.

Anyway, thank your for your work @beerlington!

**Comment by beerlington** [comment] 2016-03-16 01:01
I'm closing this because I think it's outside the scope of the gem, but please let me know if I can help with anything else.

**Closed by beerlington** 2016-03-16 01:01 UTC
